### ISSUE TITLE
docs: UI acting weird on firefox

### ISSUE THREAD

**Issue by roiLeo** [nuxt-modules/design-tokens#4]
### Environment

```bash
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6-27635653.88f4525`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

- `main` branch
- `yarn dev:docs`
- profit

**Screenshot**
![Screenshot 2022-07-19 at 15-52-54 Design System made easy Nuxt Design Tokens](https://user-images.githubusercontent.com/9987732/179767399-a8e18a86-f68b-4dd8-9bf6-1b489bed4953.png)

### Describe the bug

- can't click on "Star on Github" button nor "Get Started" because of `ellipsis` div, this could be fixed by using position & z-index
- Nuxt & Vue Telescope icon size

### Additional context

Tested on:
- Firefox v103.0b9 (64 bits)
- macOS Monterey v12.4

**Comment by Atinux** [comment]
Might be related to Docus for our docs

**Comment by Tahul** [comment]
It is related to Docus.
