### ISSUE TITLE
Handle color schemes / variants

### ISSUE THREAD

**Issue by Tahul** [nuxt-modules/design-tokens#7]
By discussing with @smarroufin about Prose components color schemes, we unveiled a small issue with current Design Tokens setup, which is color scheme handling.

Right now, it is not really convenient to handle multiple color schemes with your design tokens as you have to handle the switch between these by yourself.

One solution would be to handle it via `attributes` key of these tokens handling a `scheme` key that would allow the users to define variants of their tokens to be handled by different color schemes.

```ts
colors: {
	primary: {
		50: {
			value: '#d9e5ff',
			attributes: {
				schemes: {
					dark: '#001238'
				}
			}
		}
	}
}
```

That config would output:

```css
:root {
   --colors-primary-50: #d9e5ff';
}

/* Color Mode is not detected */
@media (prefers-color-scheme: dark) {
  :root {
    --colors-primary-50: #001238;
  }
}

/* Color Mode is detected */
body.dark {
  :root {
    --colors-primary-50: #001238;
  }
}
```

This would allow easy management of any color scheme, including support for color schemes defined in [Nuxt Color Mode](https://color-mode.nuxtjs.org/) module.

WDYT @Atinux ?

**Comment by pi0** [comment]
Checking types, it seems `colors` is a new namespace. I'm wondering it could be simpler:

```js
{
  colors: {
    'primary-50': '#b2e5f7',
  },
  schemes: {
    dark: {
      'primary-50': '#001238',
    }
  }
}
```

We could support nested for primary as well like this:

```js
{
  colors: {
    primary: {
      default: '#00bcd4',
      50: '#fafafa',
      100: '#f5f5f5',
    }
  },
}
```

**Comment by Atinux** [comment]
I find it a bit verbose, where I actually like the definition of DaisyUI colors where a color scheme is another preset of colors instead:

https://daisyui.com/docs/colors/

**Comment by Atinux** [comment]
I would rename it `variants` instead of `schemes` since we could support many styles (like DaisyUI), while having the `light` and `dark` compatible directly with system scheme.

I like the simplicity of:

```ts
{
  colors: {
    'primary-50': '#b2e5f7',
  },
  variants: {
    dark: {
      'primary-50': '#001238',
    }
  }
}
```

For aliases, see #9 

I like also this syntax to not have to jump between the places (mostly when it start to get big):
```ts
colors: {
  primary: {
    value: '#d9e5ff',
    variants: {
      dark: '#001238'
    }
  }
}```

**Comment by Tahul** [comment]
```
colors: {
  primary: {
    value: '#d9e5ff',
    variants: {
      dark: '#001238'
    }
  }
}
```

I like this syntax, will try an initial implementation based on this!
